<a href="https://colab.research.google.com/github/sujalbindra1012/MULTIPLE_DISEASE_PREDICTION_MODELS/blob/Ovarian_Cancer_Prediction/Ovarian_Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
!pip install chardet

Requirement already satisfied: chardet in /usr/local/lib/python3.10/dist-packages (5.2.0)

In [6]:
import chardet

# Open the file in binary mode
with open('/content/ovarian.csv', 'rb') as f:
    # Read the content of the file and detect the encoding
    result = chardet.detect(f.read())

# Display the detected encoding
print(result)

{'encoding': None, 'confidence': 0.0, 'language': None}

In [10]:
dataset = pd.read_csv('/content/ovarianCancer.csv')

In [11]:
dataset.head()

,SUBJECT_ID,AFP,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,...,NEU,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA
0,4,2.75,16.60,45,39.2,26.0,16.0,17.0,0.05,0.74,...,65.5,0.250,17.4,1.25,339,4.01,14.6,10.9,66.1,215.6
1,6,3.79,17.39,44,32.9,118.0,51.0,32.0,0.02,0.42,...,86.8,0.265,19.1,0.68,279,4.44,21.7,8.1,72.3,218.2
2,10,4.7,16.86,30,40.8,77.0,16.0,12.0,0.08,1.23,...,43.4,0.228,16.9,1.46,348,5.05,14.0,8.4,71.9,210.3
3,14,2.13,20.68,61,38.9,71.0,16.0,17.0,0.01,0.17,...,87.2,0.189,16.8,1.14,254,3.89,13.7,3.8,68.5,137.6
4,15,4.34,24.98,60,32.8,70.0,35.0,41.0,0.04,0.48,...,87.7,0.223,20.2,1.02,224,3.38,12.6,5.0,60.6,215.8

In [12]:
dataset.shape

(106, 51)

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 51 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SUBJECT_ID  106 non-null    int64
 1   AFP         106 non-null    object
 2   AG          106 non-null    float64
 3   Age         106 non-null    int64
 4   ALB         106 non-null    float64
 5   ALP         106 non-null    float64
 6   ALT         106 non-null    float64
 7   AST         106 non-null    float64
 8   BASO#       106 non-null    float64
 9   BASO%       106 non-null    float64
 10  BUN         106 non-null    float64
 11  Ca          106 non-null    float64
 12  CA125       106 non-null    object
 13  CA19-9      106 non-null    object
 14  CA72-4      106 non-null    float64
 15  CEA         106 non-null    float64
 16  CL          106 non-null    float64
 17  CO2CP       106 non-null    float64
 18  CREA        106 non-null    float64
 19  TYPE        106 non-null    int64
 20  DBIL        106 non-null    float64
 21  EO#         106 non-null    float64
 22  EO%         106 non-null    float64
 23  GGT         106 non-null    float64
 24  GLO         106 non-null    float64
 25  GLU.        106 non-null    float64
 26  HCT         106 non-null    float64
 27  HE4         106 non-null    float64
 28  HGB         106 non-null    float64
 29  IBIL        106 non-null    float64
 30  K           106 non-null    float64
 31  LYM#        106 non-null    float64
 32  LYM%        106 non-null    float64
 33  MCH         106 non-null    float64
 34  MCV         106 non-null    float64
 35  Menopause   106 non-null    int64
 36  Mg          106 non-null    float64
 37  MONO#       106 non-null    float64
 38  MONO%       106 non-null    float64
 39  MPV         106 non-null    float64
 40  Na          106 non-null    float64
 41  NEU         106 non-null    float64
 42  PCT         106 non-null    float64
 43  PDW         106 non-null    float64
 44  PHOS        106 non-null    float64
 45  PLT         106 non-null    int64
 46  RBC         106 non-null    float64
 47  RDW         106 non-null    float64
 48  TBIL        106 non-null    float64
 49  TP          106 non-null    float64
 50  UA          106 non-null    float64
dtypes: float64(43), int64(5), object(3)
memory usage: 42.4+ KB

In [14]:
dataset.isnull().sum()

SUBJECT_ID    0
AFP           0
AG            0
Age           0
ALB           0
ALP           0
ALT           0
AST           0
BASO#         0
BASO%         0
BUN           0
Ca            0
CA125         0
CA19-9        0
CA72-4        0
CEA           0
CL            0
CO2CP         0
CREA          0
TYPE          0
DBIL          0
EO#           0
EO%           0
GGT           0
GLO           0
GLU.          0
HCT           0
HE4           0
HGB           0
IBIL          0
K             0
LYM#          0
LYM%          0
MCH           0
MCV           0
Menopause     0
Mg            0
MONO#         0
MONO%         0
MPV           0
Na            0
NEU           0
PCT           0
PDW           0
PHOS          0
PLT           0
RBC           0
RDW           0
TBIL          0
TP            0
UA            0
dtype: int64

In [15]:
dataset.describe()

,SUBJECT_ID,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,...,NEU,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA
count,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,...,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000
mean,143.367925,19.377642,41.858491,40.059434,71.047170,19.179245,15.584906,0.041509,0.713302,4.066604,...,64.158491,0.205868,16.896038,1.088113,251.849057,4.255377,14.369151,8.347170,70.255660,236.412264
std,69.525237,2.602053,14.441632,5.396185,24.917533,10.046366,7.057408,0.024055,0.389201,1.327977,...,11.869180,0.080546,1.934412,0.173815,112.165506,0.459690,1.910137,3.050252,7.458228,65.492561
min,4.000000,13.780000,15.000000,22.000000,26.000000,10.000000,7.000000,0.000000,0.000000,1.680000,...,42.700000,0.070000,9.500000,0.680000,88.000000,3.070000,10.920000,3.300000,32.900000,96.000000
25%,83.250000,17.405000,30.000000,37.850000,55.000000,13.000000,12.000000,0.020000,0.420000,3.252500,...,55.850000,0.154250,16.425000,0.970000,191.500000,4.040000,13.200000,5.800000,66.775000,195.675000
50%,161.500000,19.540000,41.500000,40.850000,68.500000,16.000000,14.000000,0.040000,0.715000,3.915000,...,63.350000,0.190500,17.050000,1.085000,227.500000,4.250000,14.150000,8.300000,71.850000,224.050000
75%,193.750000,21.020000,51.750000,43.925000,79.000000,20.750000,17.000000,0.050000,0.955000,4.587500,...,70.950000,0.236750,17.600000,1.190000,273.500000,4.462500,15.300000,10.075000,74.675000,266.100000
max,311.000000,26.380000,74.000000,50.900000,186.000000,71.000000,51.000000,0.120000,1.940000,10.190000,...,89.300000,0.620000,20.600000,1.600000,868.000000,6.740000,22.200000,18.400000,81.100000,461.400000

In [17]:
print(dataset.columns)

Index(['SUBJECT_ID', 'AFP', 'AG', 'Age', 'ALB', 'ALP', 'ALT', 'AST', 'BASO#',
       'BASO%', 'BUN', 'Ca', 'CA125', 'CA19-9', 'CA72-4', 'CEA', 'CL', 'CO2CP',
       'CREA', 'TYPE', 'DBIL', 'EO#', 'EO%', 'GGT', 'GLO', 'GLU.', 'HCT',
       'HE4', 'HGB', 'IBIL', 'K', 'LYM#', 'LYM%', 'MCH', 'MCV', 'Menopause',
       'Mg', 'MONO#', 'MONO%', 'MPV', 'Na', 'NEU', 'PCT', 'PDW', 'PHOS', 'PLT',
       'RBC', 'RDW', 'TBIL', 'TP', 'UA'],
      dtype='object')

In [18]:
dataset['TYPE'].value_counts()

TYPE
1    62
0    44
Name: count, dtype: int64

In [20]:
dataset.groupby('TYPE').mean(numeric_only=True)

,SUBJECT_ID,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,...,NEU,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA
TYPE,,,,,,,,,,,,,,,,,,,,,
0,80.909091,19.773636,47.954545,36.797727,80.000000,19.318182,17.522727,0.041591,0.673182,4.270682,...,70.755227,0.230159,16.534091,1.104773,292.886364,4.229091,14.425909,7.759091,67.838636,239.554545
1,187.693548,19.096613,37.532258,42.374194,64.693548,19.080645,14.209677,0.041452,0.741774,3.921774,...,59.476935,0.188629,17.152903,1.076290,222.725806,4.274032,14.328871,8.764516,71.970968,234.182258

In [29]:
X = dataset.drop(columns=['TYPE','AFP','CA125','CA19-9'], axis=1)
Y = dataset['TYPE']

In [30]:
print(X)

     SUBJECT_ID     AG  Age   ALB    ALP   ALT   AST  BASO#  BASO%   BUN  ...  \
0             4  16.60   45  39.2   26.0  16.0  17.0   0.05   0.74  5.27  ...
1             6  17.39   44  32.9  118.0  51.0  32.0   0.02   0.42  4.47  ...
2            10  16.86   30  40.8   77.0  16.0  12.0   0.08   1.23  5.78  ...
3            14  20.68   61  38.9   71.0  16.0  17.0   0.01   0.17  4.49  ...
4            15  24.98   60  32.8   70.0  35.0  41.0   0.04   0.48  5.64  ...
..          ...    ...  ...   ...    ...   ...   ...    ...    ...   ...  ...
101         229  17.09   26  41.2   33.0  13.0  10.0   0.06   0.72  3.18  ...
102         233  22.04   52  43.7   63.0  16.0  13.0   0.05   0.85  4.07  ...
103         234  17.67   27  43.6   66.0  20.0  16.0   0.07   1.34  2.92  ...
104         301  23.00   56  35.1  105.0  12.0  20.0   0.04   0.40  2.64  ...
105         311  25.10   72  31.0   63.0  12.0  23.0   0.02   0.30  2.84  ...

      NEU    PCT   PDW  PHOS  PLT   RBC   RDW  TBIL    TP     UA
0    65.5  0.250  17.4  1.25  339  4.01  14.6  10.9  66.1  215.6
1    86.8  0.265  19.1  0.68  279  4.44  21.7   8.1  72.3  218.2
2    43.4  0.228  16.9  1.46  348  5.05  14.0   8.4  71.9  210.3
3    87.2  0.189  16.8  1.14  254  3.89  13.7   3.8  68.5  137.6
4    87.7  0.223  20.2  1.02  224  3.38  12.6   5.0  60.6  215.8
..    ...    ...   ...   ...  ...   ...   ...   ...   ...    ...
101  78.2  0.148  16.5  1.14  219  4.27  14.0   5.7  69.0  157.7
102  45.1  0.175  18.0  1.00  210  4.33  13.4   9.2  77.6  346.6
103  42.7  0.144  19.7  1.59  166  4.15  12.7  12.9  72.0  333.0
104  75.7  0.620   9.8  1.40  652  4.88  13.2   9.5  73.8  350.3
105  75.7  0.300   9.5  1.17  321  3.63  13.1   8.6  58.5  168.8

[106 rows x 47 columns]

In [31]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
101    1
102    1
103    1
104    0
105    0
Name: TYPE, Length: 106, dtype: int64

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [33]:
print(X.shape, X_train.shape, X_test.shape)

(106, 47) (84, 47) (22, 47)

In [34]:
scaler = StandardScaler()

In [35]:
print(X_train.dtypes)

SUBJECT_ID      int64
AG            float64
Age             int64
ALB           float64
ALP           float64
ALT           float64
AST           float64
BASO#         float64
BASO%         float64
BUN           float64
Ca            float64
CA72-4        float64
CEA           float64
CL            float64
CO2CP         float64
CREA          float64
DBIL          float64
EO#           float64
EO%           float64
GGT           float64
GLO           float64
GLU.          float64
HCT           float64
HE4           float64
HGB           float64
IBIL          float64
K             float64
LYM#          float64
LYM%          float64
MCH           float64
MCV           float64
Menopause       int64
Mg            float64
MONO#         float64
MONO%         float64
MPV           float64
Na            float64
NEU           float64
PCT           float64
PDW           float64
PHOS          float64
PLT             int64
RBC           float64
RDW           float64
TBIL          float64
TP            float64
UA            float64
dtype: object

In [36]:
scaler.fit(X_train)

StandardScaler()

In [37]:
X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

In [38]:
print(X_train)

[[-0.39180909  0.41825001  1.39040792 ...  1.0614901   0.68775248
  -0.09184197]
 [ 0.88647494 -1.45084352  1.09951312 ...  0.66898019 -1.43871403
  -0.6409266 ]
 [ 0.67086076 -1.15298    -0.86402684 ... -0.41042207 -0.40850044
   0.01487668]
 ...
 [ 0.51685064  0.62675447 -1.00947425 ... -1.65337013 -0.61982631
  -0.87674038]
 [-1.56228602  1.11450597  0.29955239 ...  2.14089236 -4.97842226
   2.27318089]
 [-0.1607939  -0.14396736  1.75402643 ... -0.8683503  -1.02927017
   0.39871954]]

In [39]:
model = svm.SVC(kernel='linear')

In [40]:
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [41]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

In [42]:
print('Accuracy score of training data : ', training_data_accuracy)

Accuracy score of training data :  1.0

In [43]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

In [44]:
print('Accuracy score of test data : ', test_data_accuracy)

Accuracy score of test data :  0.8636363636363636

In [46]:
input_data = (234,17.67,27,43.6,66.0,20.0,16.0,0.07,1.34,2.92,2.47,3.02,3.75,98.7,25.3,68.8,3.9,0.11,2.2,33.0,28.4,5.01,0.37,47.74,126.0,9.0,4.27,2.18,43.8,30.5,89.1,0,0.93,0.5,10.0,8.68,137.4,42.7,0.144,19.7,1.59,166,4.15,12.7,12.9,72.0,333.0)

input_data_as_numpy_array = np.asarray(input_data)


input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)


std_data = scaler.transform(input_data_reshaped)

prediction = model.predict(std_data)
print(prediction)


if (prediction[0] == 0):
  print("The lady does not have ovarian cancer")

else:
  print("The lady has ovarian cancer")

[1]
The lady has ovarian cancer

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(